// Neighborhood & city data — verified Census Bureau, GreatSchools, AreaVibes, DataUSA
// Generated: 2026-03-21
const NEIGHBORHOODS = {
  "Herington": {
    population: 2132,
    populationTrend: "declining",
    medianIncome: 68030,
    medianHomeValue: 92100,
    medianAge: 41,
    povertyRate: 6.7,
    medianRent: 916,
    vacancyRate: 18.67,
    unemploymentRate: 0,
    topEmployers: ["Healthcare & Social Assistance sector (154 workers)", "Educational Services (132 workers)", "Manufacturing (93 workers)", "Herington Municipal Hospital", "USD 487 Herington Schools"],
    topIndustries: ["Healthcare & Social Assistance", "Educational Services", "Manufacturing"],
    schoolDistrict: "Herington USD 487",
    schools: [{ name: "Herington Elementary School", type: "PK-5", rating: 5, enrollment: 0 }, { name: "Herington Middle School", type: "6-8", rating: 5, enrollment: 0 }, { name: "Herington High School", type: "9-12", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Herington Municipal Hospital", distance: "In town" },
    nearestGrocery: { name: "Local grocery stores available in town", distance: "In town" },
    distances: { "Topeka": "92 mi (82 min)", "Wichita": "84 mi (83 min)", "Kansas City": "155 mi (145 min)", "Fort Riley": "29 mi (35 min)" },
    landmarks: ["Tri-County Free Fair (annual July event with rodeo, parade, demolition derby)", "Kay's Pharmacy old-fashioned soda fountain", "Herington City Pool (1937 WPA-era historic pool)", "Father Padilla Memorial Park", "Herington Reservoir"],
    walkScoreLabel: "Car-Dependent (rural community)",
    crimeRate: "41% lower than national average",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "stable"
  },
  "Abilene": {
    population: 6449,
    populationTrend: "stable/slight decline",
    medianIncome: 57924,
    medianHomeValue: 156600,
    medianAge: 43,
    povertyRate: 8.09,
    medianRent: 797,
    vacancyRate: 6.36,
    unemploymentRate: 4.4,
    topEmployers: ["Memorial Health System", "Abilene Public Schools USD 435", "Dickinson County government", "Russell Stover Chocolates", "Great Plains Manufacturing"],
    topIndustries: ["Healthcare", "Education", "Manufacturing", "Agriculture", "Tourism"],
    schoolDistrict: "Abilene USD 435",
    schools: [{ name: "Abilene Elementary School", type: "PK-5", rating: 5, enrollment: 0 }, { name: "Abilene Middle School", type: "6-8", rating: 5, enrollment: 0 }, { name: "Abilene High School", type: "9-12", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Memorial Health System", distance: "In town" },
    nearestGrocery: { name: "Multiple grocery stores in town (Walmart, Dillons)", distance: "In town" },
    distances: { "Topeka": "88 mi (80 min)", "Wichita": "95 mi (90 min)", "Kansas City": "155 mi (140 min)", "Fort Riley": "32 mi (35 min)" },
    landmarks: ["Eisenhower Presidential Library & Museum (22-acre campus)", "Greyhound Hall of Fame", "Heritage Center of Dickinson County", "Abilene & Smoky Valley Railroad (scenic train rides)", "Old Abilene Town (historic Wild West site)", "Seelye Mansion (historic Georgian mansion)"],
    walkScoreLabel: "Car-Dependent (small city)",
    crimeRate: "38% lower than national average",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "rising (up 35% since 2011)"
  },
  "Emporia": {
    population: 24526,
    populationTrend: "stable/slight growth",
    medianIncome: 51111,
    medianHomeValue: 146700,
    medianAge: 34.3,
    povertyRate: 19.6,
    medianRent: 837,
    vacancyRate: 0,
    unemploymentRate: 0,
    topEmployers: ["Simmons Pet Food (1,613 employees)", "Emporia Public Schools USD 253 (928 employees)", "Emporia State University (644 employees)", "Hill's Pet Nutrition (143 employees)", "Flint Hills Technical College (83 employees)"],
    topIndustries: ["Manufacturing", "Healthcare & Social Assistance", "Retail Trade"],
    schoolDistrict: "Emporia USD 253",
    schools: [{ name: "Six elementary schools (K-5 and one K-8)", type: "elementary", rating: 5, enrollment: 0 }, { name: "Emporia Middle School", type: "middle", rating: 5, enrollment: 0 }, { name: "Emporia High School", type: "9-12", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Newman Regional Health", distance: "In town" },
    nearestGrocery: { name: "Walmart, Dillons, and other stores in town", distance: "In town" },
    distances: { "Topeka": "58 mi (60 min)", "Wichita": "87 mi (90 min)", "Kansas City": "108 mi (100 min)", "Fort Riley": "81 mi (90 min)" },
    landmarks: ["Emporia State University campus", "National Teachers Hall of Fame", "Flint Hills Trail (longest rail-trail in Kansas)", "Unbound Gravel (world-famous gravel bike race)", "Dynamic Discs Open (disc golf)", "David Traylor Zoo"],
    walkScoreLabel: "Somewhat Walkable",
    crimeRate: "17% higher than national average (property crime driven)",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "rising"
  },
  "Junction City": {
    population: 22167,
    populationTrend: "stable/slight decline",
    medianIncome: 58876,
    medianHomeValue: 161100,
    medianAge: 28,
    povertyRate: 17.9,
    medianRent: 880,
    vacancyRate: 0,
    unemploymentRate: 0,
    topEmployers: ["Fort Riley / U.S. Army (largest regional employer)", "Geary Community Hospital", "Geary County USD 475", "Walmart", "City of Junction City"],
    topIndustries: ["Military/Government", "Healthcare", "Education", "Retail"],
    schoolDistrict: "Geary County USD 475",
    schools: [{ name: "14 elementary schools", type: "elementary", rating: 5, enrollment: 0 }, { name: "2 middle schools", type: "middle", rating: 5, enrollment: 0 }, { name: "Junction City High School (career academy focused)", type: "high", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Geary Community Hospital", distance: "In town" },
    nearestGrocery: { name: "Walmart, Dillons, and other stores in town", distance: "In town" },
    distances: { "Topeka": "65 mi (60 min)", "Wichita": "130 mi (120 min)", "Kansas City": "128 mi (120 min)", "Fort Riley": "10 mi (17 min)" },
    landmarks: ["Milford Lake (largest lake in Kansas, 'Fishing Capital of Kansas')", "Republican River Trail (5-mile riverwalk)", "Heritage Park (Civil War Arch, veteran memorials)", "Konza Prairie (8,600-acre tallgrass prairie preserve)", "Fort Riley museums and historic sites", "C.L. Hoover Opera House"],
    walkScoreLabel: "Car-Dependent",
    crimeRate: "65% higher than national average",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "rising (up 40% since 2011)"
  },
  "Manhattan": {
    population: 55393,
    populationTrend: "growing",
    medianIncome: 52363,
    medianHomeValue: 217500,
    medianAge: 26,
    povertyRate: 26.9,
    medianRent: 1047,
    vacancyRate: 0,
    unemploymentRate: 0,
    topEmployers: ["Kansas State University (21,000+ students, major employer)", "Fort Riley / U.S. Army (nearby)", "Mercy Regional Health Center", "Manhattan-Ogden USD 383", "City of Manhattan"],
    topIndustries: ["Education", "Military/Government", "Healthcare", "Research/Biotech"],
    schoolDistrict: "Manhattan-Ogden USD 383",
    schools: [{ name: "Multiple elementary schools", type: "elementary", rating: 5, enrollment: 0 }, { name: "Manhattan Middle School", type: "middle", rating: 5, enrollment: 0 }, { name: "Manhattan High School", type: "high", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Ascension Via Christi Hospital (formerly Mercy Regional)", distance: "In town" },
    nearestGrocery: { name: "Walmart, Dillons, Hy-Vee, and other stores in town", distance: "In town" },
    distances: { "Topeka": "57 mi (52 min)", "Wichita": "120 mi (115 min)", "Kansas City": "120 mi (120 min)", "Fort Riley": "11 mi (15 min)" },
    landmarks: ["Kansas State University campus", "Aggieville (oldest entertainment district in Kansas, ~100 bars/restaurants/shops)", "Flint Hills Discovery Center", "Konza Prairie Nature Trail (2/4/6 mile loops)", "Sunset Zoo (300+ animals, 100+ species)", "Tuttle Creek Lake"],
    walkScoreLabel: "Somewhat Walkable (college town)",
    crimeRate: "2% lower than Kansas average",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "rising"
  },
  "Hutchinson": {
    population: 39517,
    populationTrend: "stable",
    medianIncome: 0,
    medianHomeValue: 125000,
    medianAge: 38,
    povertyRate: 15.2,
    medianRent: 889,
    vacancyRate: 0,
    unemploymentRate: 0,
    topEmployers: ["Hutchinson Regional Healthcare System (largest employer in Reno County)", "Tyson Prepared Foods", "Collins Bus Corporation (school bus manufacturing)", "Siemens Gamesa (wind energy)", "Morton Salt"],
    topIndustries: ["Healthcare", "Manufacturing", "Food Processing", "Education", "Salt Mining"],
    schoolDistrict: "Hutchinson USD 308",
    schools: [{ name: "Multiple elementary schools", type: "elementary", rating: 5, enrollment: 0 }, { name: "Hutchinson Middle School", type: "middle", rating: 5, enrollment: 0 }, { name: "Hutchinson High School", type: "high", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Hutchinson Regional Medical Center (199-bed acute care)", distance: "In town" },
    nearestGrocery: { name: "Walmart, Dillons, and other stores in town", distance: "In town" },
    distances: { "Topeka": "115 mi (110 min)", "Wichita": "41 mi (45 min)", "Kansas City": "185 mi (170 min)", "Fort Riley": "110 mi (105 min)" },
    landmarks: ["Strataca / Kansas Underground Salt Museum (650 feet underground, only tourist-accessible salt mine in US)", "Cosmosphere (Smithsonian-affiliated space museum, largest combined US/Soviet space artifact collection)", "Kansas State Fair (annual September event)", "Fox Theatre (restored 1931 art deco cinema)", "Dillon Nature Center"],
    walkScoreLabel: "Somewhat Walkable",
    crimeRate: "17% higher than national average",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "rising"
  },
  "Ogden": {
    population: 1656,
    populationTrend: "declining (down 6% since 2000)",
    medianIncome: 65139,
    medianHomeValue: 149700,
    medianAge: 30,
    povertyRate: 4.7,
    medianRent: 1164,
    vacancyRate: 20.11,
    unemploymentRate: 0,
    topEmployers: ["Fort Riley / U.S. Army (primary economic driver)", "Kansas State University (nearby in Manhattan)", "City of Ogden"],
    topIndustries: ["Military/Government", "Education", "Services"],
    schoolDistrict: "Manhattan-Ogden USD 383",
    schools: [{ name: "Ogden Elementary School (Blue Ribbon School)", type: "K-5", rating: 5, enrollment: 0 }, { name: "Manhattan Middle School (in Manhattan)", type: "middle", rating: 5, enrollment: 0 }, { name: "Manhattan High School (in Manhattan)", type: "high", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Ascension Via Christi Hospital (Manhattan)", distance: "7 mi" },
    nearestGrocery: { name: "Stores in Manhattan (7 miles east)", distance: "7 mi" },
    distances: { "Topeka": "65 mi (60 min)", "Wichita": "130 mi (120 min)", "Kansas City": "130 mi (125 min)", "Fort Riley": "5.6 mi (10 min)" },
    landmarks: ["Ogden Gate (primary Fort Riley access point)", "Adjacent to Fort Riley military installation", "Close to Manhattan and all its amenities", "Milford Lake (nearby)"],
    walkScoreLabel: "Car-Dependent",
    crimeRate: "None",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "stable"
  },
  "Hope": {
    population: 313,
    populationTrend: "declining (down 15.9% since 2000)",
    medianIncome: 47202,
    medianHomeValue: 114439,
    medianAge: 45,
    povertyRate: 36.5,
    medianRent: 0,
    vacancyRate: 0,
    unemploymentRate: 0,
    topEmployers: ["Rural Vista Schools USD 481", "Agriculture (farming/ranching)", "Small local businesses"],
    topIndustries: ["Agriculture", "Education"],
    schoolDistrict: "Rural Vista USD 481",
    schools: [{ name: "Hope Elementary School", type: "PK-8", rating: 5, enrollment: 0 }, { name: "Hope High School", type: "9-12", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Memorial Health System (Herington location)", distance: "10 mi" },
    nearestGrocery: { name: "Grocery stores in Herington (10 miles) or Abilene (20 miles)", distance: "10 mi" },
    distances: { "Topeka": "100 mi (95 min)", "Wichita": "80 mi (80 min)", "Kansas City": "165 mi (155 min)", "Fort Riley": "40 mi (45 min)" },
    landmarks: ["Hope Community Museum", "Historic connection to President Eisenhower (parents lived here 1885)", "Rural Flint Hills setting"],
    walkScoreLabel: "Car-Dependent (rural)",
    crimeRate: "None",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "stable/low"
  },
  "White City": {
    population: 447,
    populationTrend: "declining",
    medianIncome: 35417,
    medianHomeValue: 66861,
    medianAge: 43,
    povertyRate: 0,
    medianRent: 0,
    vacancyRate: 0,
    unemploymentRate: 8.2,
    topEmployers: ["Rural Vista Schools USD 481", "Agriculture (farming/ranching)", "Small local businesses"],
    topIndustries: ["Agriculture", "Education"],
    schoolDistrict: "Rural Vista USD 481",
    schools: [{ name: "White City Elementary (part of Rural Vista)", type: "elementary", rating: 5, enrollment: 0 }, { name: "White City High School", type: "9-12", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Morris County Hospital (Council Grove)", distance: "16 mi" },
    nearestGrocery: { name: "Council Grove (16 miles) or Herington (18 miles)", distance: "16 mi" },
    distances: { "Topeka": "75 mi (70 min)", "Wichita": "100 mi (95 min)", "Kansas City": "140 mi (135 min)", "Fort Riley": "50 mi (50 min)" },
    landmarks: ["Rural Flint Hills prairie setting", "Council Grove (16 miles) - historic Santa Fe Trail town", "Tallgrass prairie landscapes"],
    walkScoreLabel: "Car-Dependent (rural)",
    crimeRate: "63% lower than national average (county level)",
    climate: "Zone 4A (Mixed-Humid)",
    marketTrend: "flat/declining"
  },
  "Meade": {
    population: 1436,
    populationTrend: "declining",
    medianIncome: 71641,
    medianHomeValue: 104929,
    medianAge: 0,
    povertyRate: 3.4,
    medianRent: 747,
    vacancyRate: 0,
    unemploymentRate: 0,
    topEmployers: ["Meade District Hospital / Artesian Valley Health System", "Meade USD 226", "Agriculture (farming/ranching/feedlots)", "Meade County government"],
    topIndustries: ["Agriculture", "Healthcare", "Education", "Government"],
    schoolDistrict: "Meade USD 226",
    schools: [{ name: "Meade Elementary School", type: "elementary", rating: 5, enrollment: 0 }, { name: "Meade Junior High School", type: "middle", rating: 5, enrollment: 0 }, { name: "Meade High School", type: "high", rating: 5, enrollment: 0 }],
    nearestHospital: { name: "Meade District Hospital (20-bed critical access + 45-bed long-term care)", distance: "In town" },
    nearestGrocery: { name: "Local grocery store in town", distance: "In town" },
    distances: { "Topeka": "290 mi (270 min)", "Wichita": "173 mi (179 min)", "Kansas City": "350 mi (320 min)", "Fort Riley": "250 mi (240 min)" },
    landmarks: ["Meade State Park (803 acres, 80-acre fishing lake, camping)", "Dalton Gang Hideout & Museum", "Big Basin Prairie Preserve", "St. Jacob's Well", "Meade County Historical Society Museum"],
    walkScoreLabel: "Car-Dependent (rural/remote)",
    crimeRate: "None",
    climate: "Zone 4A (Mixed-Dry)",
    marketTrend: "stable"
  },
};

function getNeighborhood(prop) { return NEIGHBORHOODS[prop.city] || null; }