// Property data derived from Peterpan Corp portfolio records
// Coordinates geocoded via Nominatim/OpenStreetMap — verified March 2026
const PROPERTIES = [
  {
    id: "abilene-121-ne-5th",
    address: "121 NE 5th St",
    city: "Abilene",
    state: "KS",
    zip: "67410",
    county: "Dickinson",
    title: "The Abilene Campus",
    subtitle: "17,000 SqFt of Endless Potential",
    type: "Commercial / Community Facility",
    status: "Community Development",
    purchasePrice: 86000,
    estimatedValue: 252000,
    taxAssessed: 137470,
    annualTax: 5573.64,
    buildingSqft: 15781,
    landSqft: 24467,
    totalSqft: 17768,
    yearBuilt: "1916",
    legalDesc: "KUNEY AND HODGES ADDITION, S16, T13, R02, BLOCK 25, Lot 22-26, INC E 10' LOT 21, LESS R/W",
    coords: { lat: 38.9194941, lng: -97.213004 },
    features: [
      "15+ classrooms with natural lighting",
      "6 multi-stall ADA-compliant bathrooms",
      "Massive assembly hall with stage",
      "Original stained glass windows",
      "Historic pipe organ",
      "60+ paved parking stalls across 2 lots",
      "Full commercial kitchen",
      "Central HVAC system"
    ],
    description: "Located in the heart of Eisenhower's hometown, this massive 17,768 sqft facility (formerly Community Bible Church, built 1916) is a turnkey solution for community programs and childcare. Features original stained glass windows, an intact pipe organ, 15+ classrooms, and two dedicated parking lots with 60+ paved stalls. Zoned R-3 with grandfathered commercial/assembly use. Capacity for 150+ children in a licensed daycare configuration. At less than $6 per square foot, this is an extraordinary value.",
    mission: "Planned as a 150+ capacity childcare center serving Fort Riley military families, with community event space and after-school programs.",
    includedParcels: [
      { address: "100 Blk NE 6th St, Abilene", use: "Parking Lot (East)", sqft: 9177, assessed: 21350, legal: "KUNEY AND HODGES ADDITION, S16, T13, R02, BLOCK 25, Lot 1-2" },
      { address: "200 Blk NE 6th St, Abilene", use: "Parking Lot (West)", sqft: 9174, assessed: 19220, legal: "KUNEY AND HODGES ADDITION, S16, T13, R02, BLOCK 24, Lot 12-13" }
    ],
    category: "community",
    highlight: true
  },
  {
    id: "emporia-511-commercial",
    address: "511 Commercial St",
    city: "Emporia",
    state: "KS",
    zip: "66801",
    county: "Lyon",
    title: "The Commercial Street Center",
    subtitle: "Mixed-Use Community & Enterprise Hub",
    type: "Commercial / Mixed-Use",
    status: "Active Development",
    purchasePrice: 117000,
    estimatedValue: 120030,
    taxAssessed: 120030,
    annualTax: 5128.62,
    buildingSqft: 39000,
    landSqft: 13000,
    totalSqft: 13000,
    yearBuilt: "1890",
    legalDesc: "EMPORIA (O.T.), S15, T19S, R11E, ACRES 0.2, ODD LTS 155-161 COMMERCIAL ST",
    coords: { lat: 38.4043768, lng: -96.1805809 },
    features: [
      "Historic downtown storefront",
      "Street-front retail visibility",
      "Rear logistics access",
      "Multi-story with housing potential",
      "Located in grant-eligible historic district",
      "Near Emporia State University",
      "HEAL Grant & Historic Tax Credit eligible",
      "Central to downtown revitalization zone"
    ],
    description: "Located at the epicenter of Emporia's historic downtown within the Downtown Emporia Historic District, 511 Commercial St is a mixed-use community space in development. With a classic storefront facing high-traffic Commercial Street and rear access for logistics, this building is positioned to house nonprofit services on the ground floor with affordable housing units above. Eligible for HEAL Grants, Historic Tax Credits (45%), and 0% interest community development loans.",
    mission: "Ground floor: community services center and artisan market supporting local entrepreneurs. Upper floors: 6 affordable housing units for Emporia State University students and community members.",
    category: "mixed-use",
    highlight: true
  },
  {
    id: "herington-200-kansas",
    address: "200 Kansas Ave",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "The Kansas Avenue Community Grounds",
    subtitle: "5 Bed / 3 Bath — 6.4 Acres",
    type: "Event Venue / Community Space",
    status: "Planned Development",
    beds: 5,
    baths: 3,
    purchasePrice: 25000,
    estimatedValue: 124000,
    taxAssessed: 24820,
    annualTax: 374.84,
    buildingSqft: 2780,
    landSqft: 235224,
    totalSqft: 2780,
    yearBuilt: "1910",
    legalDesc: "CALKINS ADD TO HERINGTON, S01, T16, R04, LOTS 1-5 & 10-14, BLK 2, LOTS 1-6 & 10-14, BLK 3, INC VAC STS & ALLEYS ADJ",
    coords: { lat: 38.683165, lng: -96.941247 },
    features: [
      "6.4 acres within city limits",
      "2,780 sqft event structure",
      "Adjacent to City Garden & schools",
      "Open floor plan built for gatherings",
      "Indoor/outdoor event capability",
      "Ample on-site parking",
      "City water and utilities connected",
      "Walkable to downtown Herington"
    ],
    description: "A colonial two-story on a massive 6.4-acre parcel within city limits. Main floor features living room, eat-in kitchen, laundry, 3 bedrooms and 2 bathrooms. Second floor has kitchenette, bathroom, and 2 additional bedrooms. Sits on approximately 1 acre with 5.4 additional wooded acres adjacent to City Garden and schools. Sold AS IS — a once-in-a-generation canvas for community development.",
    mission: "Planned as Herington's premier community event center — hosting affordable weddings, nonprofit fundraisers, youth programs, and seasonal farmers markets on the 6-acre grounds.",
    image: "/images/properties/herington-200-kansas/1.jpg",
    includedParcels: [
      { address: "200 Blk E Logan Ave, Herington", use: "Adjacent Land (1 acre)", sqft: 43560, assessed: 3030, legal: "CALKINS ADD TO HERINGTON, S01, T16, R04, BLOCK 2, Lot 15-18" }
    ],
    category: "events",
    highlight: true
  },
  {
    id: "junction-city-337-w-7th",
    address: "337 W 7th St",
    city: "Junction City",
    state: "KS",
    zip: "66441",
    county: "Geary",
    title: "The Limestone Sanctuary",
    subtitle: "Historic Landmark — A Kansas Masterpiece",
    type: "Historic / Community Facility",
    status: "Preservation & Development",
    purchasePrice: 151000,
    estimatedValue: 154500,
    taxAssessed: 53480,
    annualTax: 1892.76,
    buildingSqft: 2771,
    landSqft: 12880,
    totalSqft: 12880,
    yearBuilt: "1942",
    legalDesc: "JCT CITY PL, BLOCK 30, Lot 9-10, SECTION 12 TOWNSHIP 12 RANGE 05",
    coords: { lat: 39.0290321, lng: -96.8350562 },
    features: [
      "Beautiful native limestone construction",
      "Wood vaulted ceilings in sanctuary",
      "Original stained glass windows",
      "Full commercial kitchen",
      "Multiple multipurpose rooms",
      "Large fenced outdoor area",
      "Minutes from Fort Riley",
      "Neighboring duplex available separately"
    ],
    description: "A beautiful limestone church building with great potential. Built in 1942, 337 W 7th St features stunning wood vaulted ceilings, original stained glass windows in the sanctuary, a full kitchen, and multiple multipurpose rooms throughout. The large fenced exterior area offers extra security for outdoor activities. Located minutes from Fort Riley, it serves a community with deep military roots and ongoing need for family services.",
    mission: "Envisioned as a Veteran & Family Resource Center providing support services, community gathering space, and cultural programs for the Fort Riley military community.",
    image: "/images/properties/junction-city-337/1.jpg",
    gallery: [
      "/images/properties/junction-city-337/1.jpg",
      "/images/properties/junction-city-337/2.jpg",
      "/images/properties/junction-city-337/3.jpg",
      "/images/properties/junction-city-337/4.jpg",
      "/images/properties/junction-city-337/5.jpg",
      "/images/properties/junction-city-337/6.jpg"
    ],
    category: "community",
    highlight: true
  },
  {
    id: "hutchinson-402-e-1st",
    address: "402 E 1st Ave",
    city: "Hutchinson",
    state: "KS",
    zip: "67501",
    county: "Reno",
    title: "The Victorian Heritage House",
    subtitle: "1894 Historic Estate — 5 Bed / 4 Bath",
    type: "Residential / Affordable Housing",
    status: "Rehabilitation Planned",
    beds: 5,
    baths: 4,
    purchasePrice: 34500,
    estimatedValue: 190300,
    taxAssessed: 27300,
    annualTax: 898.82,
    buildingSqft: 2941,
    landSqft: 16324,
    totalSqft: 16324,
    yearBuilt: "1894",
    legalDesc: "1ST EAST ORIG. TOWN, S13, T23, R06W, BLOCK 1 E, LOTS 104, 106 & 108",
    coords: { lat: 38.053527, lng: -97.9242089 },
    features: [
      "Nearly 3,000 sqft Victorian home",
      "Built 1894 — historic character",
      "Corner lot with generous yard",
      "Detached guest cottage",
      "High ceilings and original woodwork",
      "Near downtown revitalization zone",
      "Historic preservation grant eligible",
      "Multi-unit conversion potential"
    ],
    description: "Step into history with this sprawling 1894 Victorian estate. Boasting nearly 3,000 square feet, this corner-lot residence offers the grandeur of a bygone era with high ceilings, original woodwork, and a detached guest cottage. Located near downtown Hutchinson's revitalization district, this property is being rehabilitated as affordable workforce housing.",
    mission: "Being restored as affordable multi-family housing with a detached guest cottage for transitional housing support. Historic preservation maintains neighborhood character while creating accessible homes.",
    category: "housing",
    highlight: true
  },
  {
    id: "manhattan-1509-pierre",
    address: "1509 Pierre St",
    city: "Manhattan",
    state: "KS",
    zip: "66502",
    county: "Riley",
    title: "Pierre Street Residence",
    subtitle: "2 Bed / 1 Bath — Near K-State",
    type: "Residential / Affordable Housing",
    status: "Active Rental",
    beds: 2,
    baths: 1,
    purchasePrice: 35000,
    estimatedValue: 107300,
    taxAssessed: 79600,
    annualTax: 1229.98,
    buildingSqft: 807,
    landSqft: 7500,
    totalSqft: 7500,
    yearBuilt: "1890",
    legalDesc: "WARD 6, Lot 275 Plat Book/Page A /54-8",
    coords: { lat: 39.1772325, lng: -96.58057 },
    features: [
      "Blocks from Kansas State University",
      "Walking distance to Aggieville district",
      "Consistent rental demand",
      "Updated interior finishes",
      "Low-maintenance landscaping",
      "Off-street parking",
      "Near public transit routes",
      "Affordable price point"
    ],
    description: "Just blocks from Kansas State University and the vibrant Aggieville district, 1509 Pierre St provides stable, affordable housing in Manhattan's tight rental market. In a city where university enrollment drives consistent demand, this property ensures accessible housing for students and local workforce members alike.",
    mission: "Providing affordable, well-maintained rental housing for Kansas State University students and Manhattan workforce members at below-market rates.",
    category: "housing"
  },
  {
    id: "manhattan-1020-colorado",
    address: "1020 Colorado St",
    city: "Manhattan",
    state: "KS",
    zip: "66502",
    county: "Riley",
    title: "Colorado Street Home",
    subtitle: "2 Bed / 1 Bath — Near K-State",
    type: "Residential / Affordable Housing",
    status: "Active Rental",
    beds: 2,
    baths: 1,
    purchasePrice: 65000,
    estimatedValue: 95000,
    taxAssessed: 51000,
    annualTax: 781.28,
    buildingSqft: 660,
    landSqft: 7500,
    totalSqft: 7500,
    yearBuilt: "1920",
    legalDesc: "WARD 5, Lot 406 Plat Book/Page A /54-8",
    coords: { lat: 39.1765034, lng: -96.5728462 },
    features: [
      "Near Kansas State University",
      "Walkable neighborhood",
      "University-driven rental demand",
      "Manageable lot size",
      "Affordable entry point",
      "Off-street parking available"
    ],
    description: "Situated in a quiet Manhattan neighborhood near Kansas State University, 1020 Colorado St serves the local workforce and student community. Steady demand from the university ensures this property remains a reliable source of affordable housing.",
    mission: "Below-market rental housing for Manhattan's workforce and student population, contributing to housing affordability in the university community.",
    category: "housing"
  },
  {
    id: "ogden-204-12th",
    address: "204 12th St",
    city: "Ogden",
    state: "KS",
    zip: "66517",
    county: "Riley",
    title: "Fort Riley Gateway Home",
    subtitle: "Military Workforce Housing",
    type: "Residential / Affordable Housing",
    status: "Active Rental",
    purchasePrice: 12500,
    estimatedValue: 59600,
    taxAssessed: 40100,
    annualTax: 580.14,
    buildingSqft: 663,
    landSqft: 4735,
    totalSqft: 4735,
    yearBuilt: "1950",
    legalDesc: "OGDEN CITY, BLOCK 32, Lot 3 & W9' 2",
    coords: { lat: 39.1141477, lng: -96.7067611 },
    features: [
      "Gateway to Fort Riley",
      "High demand from military families",
      "Section 8 / HUD voucher certified",
      "Quiet residential street",
      "Low maintenance design",
      "Affordable entry cost"
    ],
    description: "Ogden is the gateway to Fort Riley, and 204 12th St is perfectly positioned to serve the military community and support staff. This affordable property provides stable, quality housing for soldiers, contractors, and families needing accessible off-base options in a tight-knit community.",
    mission: "Certified affordable housing serving the Fort Riley military community with Section 8 voucher acceptance and below-market rents.",
    category: "housing"
  },
  {
    id: "herington-6-s-broadway",
    address: "6 S Broadway St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "The Broadway Gateway",
    subtitle: "Premier Downtown Visibility — HQ",
    type: "Commercial / Mixed-Use",
    status: "Headquarters",
    purchasePrice: 18500,
    estimatedValue: 99900,
    taxAssessed: 19820,
    annualTax: 1083.68,
    buildingSqft: 2968,
    landSqft: 3717,
    totalSqft: 3717,
    yearBuilt: "1910",
    legalDesc: "HERINGTON TOWN OF, S12, T16, R04, BLOCK 33, LOT 6 & N 6.5\" LOT 8",
    coords: { lat: 38.6704115, lng: -96.9435399 },
    features: [
      "First building on downtown strip",
      "High visibility corner location",
      "Original brick architecture",
      "Historic character details",
      "Mixed-use zoning",
      "Street-front retail space",
      "Second floor loft potential",
      "Facade grant eligible"
    ],
    description: "As one of the first buildings greeting visitors to Herington's downtown strip, 6 S Broadway commands attention. This property features original brick architecture and serves as Peterpan Corp's headquarters — the operational center for the organization's 19-property portfolio across Kansas.",
    mission: "Peterpan Corp headquarters and community retail space on the ground floor, with an affordable apartment unit above anchoring Herington's downtown revitalization.",
    category: "mixed-use"
  },
  {
    id: "herington-broadway-block",
    address: "112-120 S Broadway St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "The Broadway Block",
    subtitle: "Church + Annex + Garage — Community Campus",
    type: "Commercial / Community",
    status: "Active Use",
    purchasePrice: 68000,
    estimatedValue: 178800,
    taxAssessed: 74220,
    annualTax: 1639.32,
    buildingSqft: 9839,
    landSqft: 19441,
    totalSqft: 19441,
    yearBuilt: "1900–1920",
    legalDesc: "HERINGTON, ORIGINAL TOWN, S12, T16, R04, BLOCK 40",
    coords: { lat: 38.6696866, lng: -96.9435369 },
    features: [
      "Historic First Baptist Church (1900) — sanctuary seating 200+",
      "Stained glass windows and bell tower",
      "High-volume sanctuary with excellent acoustics",
      "Church kitchen and fellowship hall",
      "Sunday school classrooms and office spaces",
      "112 S Broadway annex — retail/admin (4,401 sqft)",
      "100 Blk S Broadway — dedicated garage/parking",
      "Combined 9,839 sqft across 3 buildings on Block 40"
    ],
    description: "The Broadway Block is a complete 3-building community campus spanning Block 40 of downtown Herington. The centerpiece is the historic First Baptist Church (120 S Broadway, built 1900) with its magnificent sanctuary, stained glass windows, and fellowship hall. Adjacent is the Broadway Annex (112 S Broadway) providing retail/admin space, and a dedicated garage at 100 Blk S Broadway. Together they form Peterpan Corp's primary community operations complex.",
    mission: "Community campus serving as event venue, nonprofit admin hub, and community services center. Church hosts affordable weddings, memorial services, and cultural events. Annex houses thrift store concept and housing resource office.",
    includedParcels: [
      { address: "120 S Broadway St", use: "First Baptist Church — Sanctuary & Fellowship Hall (3,753 sqft, 1900)", sqft: 8850, building: 3753, assessed: 27830, purchasePrice: 26500, annualTax: 568.74, legal: "BLOCK 40, LOTS 16, 18, 20" },
      { address: "112 S Broadway St", use: "Broadway Annex — Retail/Admin (4,401 sqft, 1920)", sqft: 8850, building: 4401, assessed: 44550, purchasePrice: 41500, annualTax: 970.58, legal: "BLOCK 40, LOTS 10, 12, 14" },
      { address: "100 Blk S Broadway St", use: "Garage / Parking", sqft: 1741, building: 1685, assessed: 1840, purchasePrice: 0, annualTax: 99.56, legal: "BLOCK 40" }
    ],
    category: "community"
  },
  {
    id: "herington-212-w-main",
    address: "212 W Main St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "Main Street Community Home",
    subtitle: "3 Bed / 1.5 Bath — Updated Systems",
    type: "Residential",
    status: "Occupied",
    beds: 3,
    baths: 1.5,
    purchasePrice: 30500,
    estimatedValue: 51000,
    taxAssessed: 29420,
    annualTax: 689.38,
    buildingSqft: 1795,
    landSqft: 4426,
    totalSqft: 4426,
    yearBuilt: "1900",
    legalDesc: "HERINGTON (BLK 118-131), S12, T16, R04, BLOCK 118, LOT 12 & W2 LOT 11",
    coords: { lat: 38.671488, lng: -96.9461417 },
    features: ["3 bedrooms, 1.5 bathrooms", "New roof installed", "New furnace and water heater", "Basement with new supports", "Garage (198 sqft)", "Covered porch (180 sqft)", "Walking distance to downtown", "Built 1900 — classic Kansas character"],
    description: "A charming 3-bedroom, 1.5-bath home on Herington's Main Street with recently updated systems including new roof, furnace, water heater, and basement supports. The 1,795 sqft home features a garage and covered porch, located steps from downtown Herington.",
    mission: "Staff housing for Peterpan Corp's Herington program director, enabling on-the-ground management of community development initiatives.",
    category: "housing"
  },
  {
    id: "herington-317-s-2nd",
    address: "317 S 2nd St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "The Second Street Manor",
    subtitle: "3 Bed / 2 Bath — Manufactured Home",
    type: "Residential / Affordable Housing",
    status: "Rehabilitation",
    beds: 3,
    baths: 2,
    purchasePrice: 16150,
    estimatedValue: 140800,
    taxAssessed: 16090,
    annualTax: 1183.58,
    buildingSqft: 1440,
    landSqft: 11800,
    totalSqft: 11800,
    yearBuilt: "1976",
    legalDesc: "HERINGTON (BLK 118-131), S12, T16, R04, BLOCK 129, LOTS 13, 15, 17, 19",
    coords: { lat: 38.6678847, lng: -96.9459677 },
    features: ["3,890 sqft spacious layout", "Generous corner lot", "Historic early 1900s charm", "Original hardwood floors", "Walking distance to downtown", "ADU or garden expansion space", "Railroad/hospital workforce proximity", "Multi-family conversion ready"],
    description: "Discover the sleeping giant of Dickinson County. This expansive property on a quiet corner lot offers the classic charm of early 20th-century architecture. With nearly 4,000 square feet of living space, original hardwood floors, and a generous lot.",
    mission: "Being restored as affordable workforce housing for local railroad and hospital employees, with potential for a secondary unit to expand housing availability.",
    category: "housing"
  },
  {
    id: "herington-202-w-walnut",
    address: "202 W Walnut St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "Walnut Street Cottage",
    subtitle: "4 Bed / 2 Bath — 1902 Historic",
    type: "Residential / Affordable Housing",
    status: "Available",
    beds: 4,
    baths: 2,
    purchasePrice: 25000,
    estimatedValue: 50000,
    taxAssessed: 23010,
    annualTax: 553.74,
    buildingSqft: 2412,
    landSqft: 5900,
    totalSqft: 5900,
    yearBuilt: "1902",
    legalDesc: "HERINGTON (BLK 118-131), S12, T16, R04, BLOCK 119, LOTS 2 & 4",
    coords: { lat: 38.6706098, lng: -96.9460446 },
    features: ["Affordable starter home", "Quiet residential street", "Near schools", "City utilities", "Fenced yard potential", "Walkable to downtown"],
    description: "A classic Kansas cottage on a quiet street, 202 W Walnut offers an affordable pathway to homeownership. Close to schools and downtown services.",
    mission: "Affordable homeownership opportunity or rental housing for Herington families, maintained at accessible price points.",
    category: "housing"
  },
  {
    id: "herington-516-e-arnold",
    address: "516 E Arnold St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "Arnold Street Home",
    subtitle: "2 Bed / 1 Bath — Workforce Housing",
    type: "Residential / Affordable Housing",
    status: "Available",
    beds: 2,
    baths: 1,
    purchasePrice: 14000,
    estimatedValue: 56500,
    taxAssessed: 16670,
    annualTax: 400.72,
    buildingSqft: 1444,
    landSqft: 7811,
    totalSqft: 7811,
    yearBuilt: "1900",
    legalDesc: "HERINGTON TWN CO ADDITION, S12, T16, R04, BLOCK 60, Lot 3-4",
    coords: { lat: 38.6741595, lng: -96.9379062 },
    features: ["Affordable family home", "Large lot", "Quiet east-side neighborhood", "Near parks", "City utilities connected", "Low tax burden"],
    description: "A practical family home on a generous lot in Herington's east side. 516 E Arnold represents the core of Peterpan Corp's affordable housing mission.",
    mission: "Affordable rental housing maintained to safe, clean, functional standards for Herington workforce families.",
    category: "housing"
  },
  {
    id: "herington-604-n-d",
    address: "604 N D St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "North D Street Home",
    subtitle: "2 Bed / 1 Bath — Cottage",
    type: "Residential / Affordable Housing",
    status: "Available",
    beds: 2,
    baths: 1,
    purchasePrice: 12000,
    estimatedValue: 60500,
    taxAssessed: 13650,
    annualTax: 503.96,
    buildingSqft: 984,
    landSqft: 7100,
    totalSqft: 7100,
    yearBuilt: "1900",
    legalDesc: "MURRAYS ADD (BLK 1), S12, T16, R04, BLOCK 1, LOTS 16 & 18",
    coords: { lat: 38.6757658, lng: -96.9394071 },
    features: ["Affordable family home", "North-side neighborhood", "Near Murray's Park", "Spacious lot", "City utilities", "Low carrying costs"],
    description: "Located in Herington's north side near Murray's Park, 604 N D St provides affordable family housing in a quiet residential setting.",
    mission: "Affordable rental housing serving north Herington families with below-market rates and responsive maintenance.",
    category: "housing"
  },
  {
    id: "hope-114-e-broadway",
    address: "114 E Broadway St",
    city: "Hope",
    state: "KS",
    zip: "67451",
    county: "Dickinson",
    title: "Hope Community Building",
    subtitle: "3 Bed / 1 Bath — 1885 Historic",
    type: "Commercial / Community",
    status: "Community Use",
    beds: 3,
    baths: 1,
    purchasePrice: 13000,
    estimatedValue: 69000,
    taxAssessed: 13000,
    annualTax: 836.26,
    buildingSqft: 1431,
    landSqft: 12095,
    totalSqft: 12095,
    yearBuilt: "1885",
    legalDesc: "HENQUENETS ADDITION, S02, T16, R03, BLOCK 2, Lot 4-6",
    coords: { lat: 38.688368, lng: -97.0685297 },
    features: ["Main Street location", "Large lot", "Open floor plan", "Community gathering space", "Near Hope schools", "Small-town charm"],
    description: "On the main street of Hope, Kansas, this building serves as a vital community gathering point. In a town where every resource matters, 114 E Broadway provides space for community meetings, educational workshops, and local events.",
    mission: "Community gathering space for Hope, KS — hosting workshops, town meetings, and youth programs that serve this tight-knit rural community.",
    category: "community"
  },
  {
    id: "white-city-124-w-mckenzie",
    address: "124 W McKenzie St",
    city: "White City",
    state: "KS",
    zip: "66872",
    county: "Morris",
    title: "McKenzie Street Property",
    subtitle: "Rural Community Support",
    type: "Residential / Community",
    status: "Assessment",
    purchasePrice: 5400,
    estimatedValue: 4390,
    taxAssessed: 4390,
    annualTax: 190.46,
    buildingSqft: 2160,
    landSqft: 3640,
    totalSqft: 3640,
    yearBuilt: "1885",
    legalDesc: "WHITE CITY ORIGINAL, S35, T14, R06E, BLOCK 23, LT 12 LYG W FIREWALL",
    coords: { lat: 38.7933, lng: -96.7411 },
    features: ["Small-town Kansas", "Affordable entry point", "Near community services", "Rural character", "Low overhead"],
    description: "In the small town of White City, this property extends Peterpan Corp's commitment to rural Kansas communities.",
    mission: "Supporting White City's housing availability as part of Peterpan Corp's rural Kansas community development network.",
    category: "housing"
  },
  {
    id: "herington-9th-street-triad",
    address: "215-217 S 9th St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "The 9th Street Triad",
    subtitle: "3 Adjacent Properties — Massive Equity Gap",
    type: "Residential / Development",
    status: "Assessment",
    purchasePrice: 13761,
    estimatedValue: 181530,
    taxAssessed: 19330,
    annualTax: 905.24,
    buildingSqft: 3948,
    landSqft: 20999,
    totalSqft: 20999,
    yearBuilt: "1920-1930",
    legalDesc: "CREECHS 2ND ADDITION, S11, T16, R04, BLOCKS 148-149",
    coords: { lat: 38.6678, lng: -96.9403 },
    features: [
      "3 adjacent lots spanning 2 blocks",
      "Combined 21,000 sqft of land",
      "3,948 sqft total building area",
      "Massive equity gap: $13.7K purchase → $181K estimated",
      "Ideal for multi-family development",
      "Quiet residential neighborhood",
      "Near Herington schools"
    ],
    description: "Three adjacent properties on South 9th Street acquired at tax-sale prices with a combined estimated market value of $181,530. The 215 and 217 parcels are in Creech's 2nd Addition Block 149, while 216 is across the street in Block 148. Together they offer 21,000 sqft of land for multi-family housing development or individual rental rehabilitation.",
    mission: "Phased rehabilitation into affordable workforce rental housing, leveraging the scale of 3 adjacent properties to reduce per-unit renovation costs.",
    includedParcels: [
      { address: "215 S 9th St", use: "Bungalow 3bd/2ba (1,080 sqft, 1930)", sqft: 6999, building: 1080, assessed: 4070, purchasePrice: 4453, annualTax: 308.44, estimatedValue: 46110, legal: "CREECHS 2ND ADD, BLOCK 149, LOTS 21 & 23" },
      { address: "216 S 9th St", use: "Cottage 2bd/1ba (864 sqft, 1920)", sqft: 7000, building: 864, assessed: 10500, purchasePrice: 10000, annualTax: 274.58, estimatedValue: 44750, legal: "CREECHS SECOND ADDITION, BLOCK 148, LOTS 22 & 24" },
      { address: "217 S 9th St", use: "Cottage 2bd/1ba (568 sqft, 1930)", sqft: 7000, building: 568, assessed: 4760, purchasePrice: 4855, annualTax: 322.22, estimatedValue: 90670, legal: "CREECHS 2ND ADD, BLOCK 149, LOTS 17 & 19" }
    ],
    category: "housing"
  },
  {
    id: "herington-walnut-pair",
    address: "12-14 W Walnut St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "The Walnut Street Pair",
    subtitle: "Adjacent Downtown Retail — Commercial",
    type: "Commercial / Mixed-Use",
    status: "Available",
    purchasePrice: 23384,
    estimatedValue: 105000,
    taxAssessed: 23070,
    annualTax: 833.00,
    buildingSqft: 6451,
    landSqft: 5901,
    totalSqft: 5901,
    yearBuilt: "c. 1910",
    legalDesc: "HERINGTON TOWN OF, S12, T16, R04, BLOCK 29",
    coords: { lat: 38.6706, lng: -96.9462 },
    features: [
      "2 adjacent lots on Block 29",
      "Combined 6,451 sqft building area",
      "Downtown adjacent location",
      "Corner visibility",
      "Residential or mixed-use zoning",
      "Walkable to Broadway commercial strip"
    ],
    description: "Two adjacent properties on West Walnut Street at the edge of downtown Herington. Combined, they offer over 6,400 sqft of building space on Block 29 — ideal for a small multi-family conversion or home-business operation. The corner position provides visibility and access.",
    mission: "Affordable workforce housing or home-business incubator supporting Herington's local economy.",
    includedParcels: [
      { address: "12 W Walnut St", use: "Downtown Row Store — Retail (3,300 sqft, 1900)", sqft: 3541, building: 3300, assessed: 8990, purchasePrice: 9884, annualTax: 524.44, estimatedValue: 43000, legal: "BLOCK 29, LOT 12 & E 5' LOT 14" },
      { address: "14 W Walnut St", use: "Downtown Row Store — 'Taco Stop' (3,151 sqft, 1900)", sqft: 2360, building: 3151, assessed: 14080, purchasePrice: 13500, annualTax: 308.54, estimatedValue: 62000, legal: "BLOCK 29, W 20' LOT 14" }
    ],
    category: "housing"
  },
  {
    id: "herington-317-w-walnut",
    address: "317 W Walnut St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "West Walnut Workshop",
    subtitle: "7,700 SqFt Warehouse — Commercial",
    type: "Residential / Workshop",
    status: "Available",
    purchasePrice: 4393,
    estimatedValue: 42600,
    taxAssessed: 2760,
    annualTax: 201.52,
    buildingSqft: 7700,
    landSqft: 14500,
    totalSqft: 14500,
    yearBuilt: "1927",
    legalDesc: "HERINGTON (BLK 118-131), S12, T16, R04, BLOCK 121, LOTS 15, 17",
    coords: { lat: 38.6700, lng: -96.9480 },
    features: [
      "14,500 sqft lot (1/3 acre)",
      "8,060 sqft building footprint",
      "Large workshop/storage potential",
      "Low tax burden ($201/year)",
      "Quiet west-side neighborhood"
    ],
    description: "A large-lot property on Herington's west side with significant building footprint (8,060 sqft). At a $4,393 purchase price and just $201/year in taxes, this is an ultra-low-cost asset ideal for workshop, storage, or future residential development.",
    mission: "Portfolio support property — equipment storage, workshop space, or future affordable housing development site.",
    category: "housing"
  },
  {
    id: "meade-402-w-carthage",
    address: "402 W Carthage",
    city: "Meade",
    state: "KS",
    zip: "67864",
    county: "Meade",
    title: "Meade Property (Demolished)",
    subtitle: "Land Only — Structure Demolished by City",
    type: "Land",
    status: "Demolished",
    purchasePrice: 33500,
    estimatedValue: 116900,
    taxAssessed: 0,
    annualTax: 250,
    buildingSqft: 0,
    landSqft: 0,
    totalSqft: 0,
    yearBuilt: "N/A",
    legalDesc: "Meade County parcel",
    coords: { lat: 37.2856, lng: -100.3392 },
    features: [
      "Structure demolished by City of Meade",
      "Land parcel only",
      "Meade County — southwestern Kansas",
      "Realtor.com estimated $116,900 (pre-demolition)"
    ],
    description: "Former residential property in Meade, Kansas. The structure was demolished by the City. Now a vacant land parcel. Estimated pre-demolition value was $116,900 per Realtor.com. Current status requires assessment of land-only value and determination of best use — potential building site or strategic disposition.",
    mission: "Under assessment — evaluating land value for potential sale or future affordable housing development in Meade County.",
    category: "housing",
    hidden: true
  },
  {
    id: "herington-12-s-broadway",
    address: "12 S Broadway St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "Broadway Boutique",
    subtitle: "Small-Scale Commercial — Block 33",
    type: "Commercial / Mixed-Use",
    status: "Available",
    purchasePrice: 12000,
    estimatedValue: 92000,
    taxAssessed: 12600,
    annualTax: 680,
    buildingSqft: 800,
    landSqft: 2950,
    totalSqft: 2950,
    yearBuilt: "1960",
    legalDesc: "HERINGTON TOWN OF, S12, T16, R04, BLOCK 33, Lot 12",
    coords: { lat: 38.6702, lng: -96.9435 },
    features: [
      "800 sqft commercial office building",
      "Downtown Broadway location",
      "Block 33 — near HQ at 6 S Broadway",
      "Low entry cost ($12,000 purchase)",
      "Average condition per county assessor",
      "Mixed-use zoning potential"
    ],
    description: "A compact 800 sqft downtown commercial building on Broadway, just steps from Peterpan Corp's headquarters at 6 S Broadway. At a $12,000 purchase price, this is one of the most affordable commercial entries in Herington — ideal for a small office, boutique retail, or service business supporting the downtown strip.",
    mission: "Small-scale commercial space supporting Herington's downtown revitalization — available for community-serving retail or nonprofit office use.",
    category: "mixed-use"
  },
  {
    id: "herington-14-e-day",
    address: "14 E Day St",
    city: "Herington",
    state: "KS",
    zip: "67449",
    county: "Dickinson",
    title: "Day Street Project",
    subtitle: "Downtown Adjacent — Development Opportunity",
    type: "Residential / Development",
    status: "Assessment",
    purchasePrice: 5952,
    estimatedValue: 5130,
    taxAssessed: 5130,
    annualTax: 485.10,
    buildingSqft: 1080,
    landSqft: 4900,
    totalSqft: 4900,
    yearBuilt: "c. 1920",
    legalDesc: "HERINGTON TOWN OF, S12, T16, R04, BLOCK 33, BEG SW COR LOT 15",
    coords: { lat: 38.6703, lng: -96.9430 },
    features: [
      "1,080 sqft building on 4,900 sqft lot",
      "Block 33 — same block as HQ",
      "Ultra-low assessed value ($5,130)",
      "Downtown adjacent location",
      "Development or teardown candidate",
      "Near 6 S Broadway and 12 S Broadway"
    ],
    description: "A development opportunity on Day Street, sharing Block 33 with Peterpan Corp's HQ. The 1,080 sqft structure on a 4,900 sqft lot is assessed at just $5,130 — making it a candidate for renovation, teardown-and-rebuild, or lot consolidation with adjacent holdings.",
    mission: "Under assessment for best use — renovation into affordable housing, lot consolidation with Block 33 holdings, or community garden/pocket park.",
    category: "housing"
  }
];

// Generate Google Maps image URL for a property (satellite view)
function getMapImageUrl(prop, width, height) {
  const w = width || 800;
  const h = height || 400;
  // Use Google Maps Embed as iframe source — free, no API key
  return `https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d500!2d${prop.coords.lng}!3d${prop.coords.lat}!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2sus`;
}

// Generate Street View embed URL
function getStreetViewUrl(prop) {
  return `https://www.google.com/maps/embed?pb=!4v0!6m8!1m7!1s!2m2!1d${prop.coords.lat}!2d${prop.coords.lng}!3f0!4f0!5f0.7820865974627469`;
}

// Generate a direct Google Maps link
function getGoogleMapsLink(prop) {
  return `https://www.google.com/maps/search/?api=1&query=${prop.coords.lat},${prop.coords.lng}`;
}

// Active properties (exclude hidden)
const ACTIVE_PROPERTIES = PROPERTIES.filter(p => !p.hidden);
const _subParcels = ACTIVE_PROPERTIES.reduce((sum, p) => sum + (p.includedParcels ? p.includedParcels.length : 0), 0);
const PORTFOLIO_STATS = {
  totalListings: ACTIVE_PROPERTIES.length,
  totalParcels: ACTIVE_PROPERTIES.length + _subParcels,
  totalEstimatedValue: ACTIVE_PROPERTIES.reduce((sum, p) => sum + p.estimatedValue, 0),
  totalPurchasePrice: ACTIVE_PROPERTIES.reduce((sum, p) => sum + p.purchasePrice, 0),
  totalEquity: ACTIVE_PROPERTIES.reduce((sum, p) => sum + (p.estimatedValue - p.purchasePrice), 0),
  totalBuildingSqft: ACTIVE_PROPERTIES.reduce((sum, p) => sum + p.buildingSqft, 0),
  totalLandSqft: ACTIVE_PROPERTIES.reduce((sum, p) => sum + (p.landSqft || 0), 0),
  totalAnnualTax: ACTIVE_PROPERTIES.reduce((sum, p) => sum + (p.annualTax || 0), 0),
  counties: [...new Set(ACTIVE_PROPERTIES.map(p => p.county))].length,
  cities: [...new Set(ACTIVE_PROPERTIES.map(p => p.city))].length,
  avgPricePerSqft: Math.round(ACTIVE_PROPERTIES.reduce((sum, p) => sum + p.estimatedValue, 0) / ACTIVE_PROPERTIES.reduce((sum, p) => sum + (p.buildingSqft || 1), 0)),
  categories: {
    housing: ACTIVE_PROPERTIES.filter(p => p.category === "housing").length,
    community: ACTIVE_PROPERTIES.filter(p => p.category === "community").length,
    "mixed-use": ACTIVE_PROPERTIES.filter(p => p.category === "mixed-use").length,
    events: ACTIVE_PROPERTIES.filter(p => p.category === "events").length
  }
};
